---
# Network
# https://docs.rockylinux.org/guides/
worker_network:
    device: null # Network interface name e.g. eth0
    hostname: null # Hostname e.g. node01.superclustr.net
    ip_address: null # Static IP address or 'dhcp' for dynamic assignment
    ip_netmask: null # IP netmask e.g. 255.255.255.128
    ip_gateway: null # Gateway IP address e.g. 192.168.1.1
    ip_v6_address: null # Static IPv6 address or 'dhcp' for dynamic assignment
    tailscale_key: null # Tailscale authentication key https://tailscale.com/kb/1085/auth-keys

# Kubernetes
# https://kubernetes.io/docs/home/
worker_kubernetes:
    server: null # Master server e.g. node01.superclustr.net
    kubernetes_token: null # Kubernetes node token
