---
# This playbook installs all necessary packages

#######################
# Docker Installation #
#######################

- name: Install Docker Packages
  dnf:
    name: "{{ docker_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: docker-install

#########################
# Firewall Installation #
#########################

- name: Install Firewalld packages
  dnf:
    name: firewalld
    state: present
  tags: firewalld-install