---
# This playbook configures the network

###########################
# Hostname Configuration #
###########################

- name: Set hostname based on Docker Swarm Node ID
  block:
    - name: Get Docker Swarm Node ID
      command: docker info --format {% raw %}'{{.Swarm.NodeID}}'{% endraw %}
      register: docker_node_id
      changed_when: false

    - name: Set hostname
      hostname:
        name: "{{ docker_node_id.stdout }}.superclustr.net"

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ docker_node_id.stdout }}.superclustr.net"
        state: present