---
# This playbook configures the network

###########################
# Hostname Configuration #
###########################

- name: Set hostname based on Docker Swarm node name
  hosts: all
  become: yes
  tasks:
    - name: Get Docker Swarm Node Name
      command: docker info --format '{{.Name}}'
      register: docker_node_name
      changed_when: false

    - name: Set hostname
      hostname:
        name: "{{ docker_node_name.stdout | replace('-', '') }}.superclustr.net"

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ docker_node_name.stdout | replace('-', '') }}.superclustr.net"
        state: present