---
# Network
# https://docs.rockylinux.org/guides/
master_network:
    device: null # Network interface name e.g. eth0
    ip_pool: null # LoadBalancer IP pool range e.g. 192.168.1.240-192.168.1.250
    ip_address: null # Static IP address or 'dhcp' for dynamic assignment
    ip_netmask: null # IP netmask e.g. 255.255.255.128
    ip_gateway: null # Gateway IP address e.g. 192.168.1.1
    ip_v6_pool: null # LoadBalancer IPv6 pool range e.g. 2001:678:7ec:70::1/64
    ip_v6_address: null # Static IPv6 address or 'dhcp' for dynamic assignment

# Kubernetes
# https://kubernetes.io/docs/home/
master_kubernetes:
    email: hostmaster@superclustr.net

# Slurm
# https://slurm.schedmd.com/documentation.html
master_slurm:
    cluster_name: superclustr
    state_save_location: /var/spool/slurm # Absolute path for Slurm controller state (`slurm.conf` parameter StateSaveLocation)
    job_comp_loc: /var/log/slurm_jobacct.log # Absolute path for Slurm job completion logfile (`slurm.conf` parameter JobCompLoc)
