---
# Network
# https://docs.rockylinux.org/guides/
master_network:
    hostname: null # Hostname e.g. node01.superclustr.net
    device: null # Network interface name e.g. eth0
    ip_pool: null # LoadBalancer IP pool range e.g. 192.168.1.240-192.168.1.250
    ip_address: null # Static IP address or 'dhcp' for dynamic assignment
    ip_netmask: null # IP netmask e.g. 255.255.255.128
    ip_gateway: null # Gateway IP address e.g. 192.168.1.1
    ip_v6_pool: null # LoadBalancer IPv6 pool range e.g. 2001:678:7ec:70::1/64
    ip_v6_address: null # Static IPv6 address or 'dhcp' for dynamic assignment
    tailscale_token: null # Tailscale authentication token https://tailscale.com/kb/1085/auth-keys

# Kubernetes
# https://kubernetes.io/docs/home/
master_kubernetes:
    email: null # Email address e.g. hostmaster@superclustr.net
    taint: null # Taint e.g. node-role.kubernetes.io/control-plane:NoSchedule

