---
# This playbook installs all necessary packages

##########################
# Tailscale Installation #
##########################

- name: Install Tailscale
  shell: |
    curl -fsSL https://tailscale.com/install.sh | sh
  args:
    creates: /usr/bin/tailscale
  tags: tailscale-install

- name: Provision Tailscale
  command: |
    tailscale up \
      --ssh \
      --auth-key "{{ worker_network.tailscale_token }}" \
      --advertise-tags "tag:superclustr"
  register: tailscale_result
  changed_when: "'Success' in tailscale_result.stdout"
  tags: tailscale-install

- name: Get Tailscale IP address
  shell: tailscale ip -4
  register: tailscale_ip
  changed_when: false
  tags: tailscale-install

#########################
# Firewall Installation #
#########################

- name: Install Firewalld packages
  dnf:
    name: firewalld
    state: present
  tags: firewalld-install

###########################
# Kubernetes Installation #
###########################

- name: Install Kubernetes packages
  dnf:
    name: "{{ kubernetes_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: kubernetes-install

- name: Install Kubernetes (k3s)
  block:
    - name: Download k3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'

    - name: Install k3s agent
      environment:
        INSTALL_K3S_EXEC: >-
          agent
          --token "{{ worker_kubernetes.kubernetes_token }}"
          --server "https://{{ worker_kubernetes.server }}:6443"
          --node-external-ip "{{ tailscale_ip.stdout }}"
          --vpn-auth "name=tailscale,joinKey={{ worker_network.tailscale_token }}"
      shell: /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        state: present
        delay: 5
        timeout: 300
  tags: kubernetes-install