---
# This playbook installs all necessary packages

##########################
# Tailscale Installation #
##########################

- name: Install Tailscale
  shell: |
    curl -fsSL https://tailscale.com/install.sh | sh
  args:
    creates: /usr/sbin/tailscale
  tags: tailscale-install

#########################
# Firewall Installation #
#########################

- name: Install Firewalld packages
  dnf:
    name: firewalld
    state: present
  tags: firewalld-install

######################
# Slurm Installation #
######################

- name: Install Slurm packages
  dnf:
    name: "{{ slurm_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: slurm-install

###########################
# Kubernetes Installation #
###########################

- name: Install Kubernetes packages
  dnf:
    name: "{{ kubernetes_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: kubernetes-install

- name: Install Kubernetes (k3s)
  block:
    - name: Download k3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'

    - name: Install k3s server
      environment:
        INSTALL_K3S_EXEC: >-
          server
          --flannel-backend none
          --disable-network-policy
          --write-kubeconfig-mode "0644"
      shell: /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        state: present
        delay: 5
        timeout: 300
  tags: kubernetes-install

#####################
# Helm Installation #
#####################

- name: Install Helm
  shell: |
    export PATH=$PATH:/usr/local/bin
    curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  tags: helm-install

#######################
# Cilium Installation #
#######################

- name: Install Cilium
  block:
    - name: Add Cilium helm repo
      command: helm repo add cilium https://helm.cilium.io/
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    - name: Install Cilium
      command: >-
        helm install cilium cilium/cilium 
        --namespace kube-system 
        --set ipam.operator.clusterPoolIPv4PodCIDRList="10.42.0.0/16" 
        --set operator.replicas=1
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  tags: cilium-install

#######################
# ArgoCD Installation #
#######################

- name: Install ArgoCD
  block:
    - name: Add ArgoCD helm repo
      command: helm repo add argo https://argoproj.github.io/argo-helm
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    - name: Create argocd namespace
      command: kubectl create namespace argocd
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    - name: Install ArgoCD
      command: helm install argocd argo/argo-cd --namespace argocd
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  tags: argocd-install

########################
# MetalLB Installation #
########################

- name: Install MetalLB
  block:
    - name: Add MetalLB helm repo
      command: helm repo add metallb https://metallb.github.io/metallb
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    - name: Create metallb-system namespace
      command: kubectl create namespace metallb-system
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    - name: Install MetalLB
      command: >-
        helm install metallb metallb/metallb 
        --namespace metallb-system
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  tags: metallb-install

#############################
# Cert-Manager Installation #
#############################

- name: Add Jetstack Helm repo
  command: helm repo add jetstack https://charts.jetstack.io
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  failed_when: false
  tags: certmanager-install

- name: Create cert-manager namespace
  command: kubectl create namespace cert-manager
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  tags: certmanager-install

- name: Install Cert-Manager
  command: helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.14.1 --set installCRDs=true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  args:
    creates: /etc/rancher/k3s/cert-manager-installed
  tags: certmanager-install

#######################
# BeeGFS Installation #
#######################

- name: Install BeeGFS packages
  dnf:
    name: "{{ beegfs_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: beegfs-install

#######################
# ConMan Installation #
#######################

- name: Install ConMan (Console Manager) packages
  dnf:
    name: "{{ conman_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: conman-install

- name: Ensure the ConMan configuration exists but is empty
  file:
    path: /etc/conman.conf
    state: touch
    mode: '0644'
  tags: conman-config

########################
# Genders Installation #
########################

- name: Install Genders packages
  dnf:
    name: "{{ genders_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: genders-install

- name: Ensure the Genders config file exists but is empty
  file:
    path: /etc/genders
    state: touch
    mode: '0644'
  tags: genders-config

####################
# NHC Installation #
####################

- name: Install NHC (Node Health Checker) packages
  dnf:
    name: "{{ nhc_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: nhc-install
