name: Main

on:
  push:
    branches:
      - main
    tags:
      - '*'  # This triggers both builds and tag deployments

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Generates
        run: |
          make generate

      - name: Build Binary
        run: |
          make build

      # TODO: Fix tests and enable this
      #- name: Test Binary
      #  run: |
      #    make test

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: super
          path: bin/super

  deploy:
    name: Deploy to GitHub Pages on Tag
    needs: build
    if: startsWith(github.ref, 'refs/tags/')  # Only run when a tag is pushed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get the Tag Version
        id: get_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Download Binary Artifact
        uses: actions/download-artifact@v4
        with:
          name: super
          path: /tmp/artifacts

      - name: Copy to versioned and latest
        run: |
          cp /tmp/artifacts/super super-${{ env.tag }}
          cp /tmp/artifacts/super super

      - name: Commit and Push Changes
        run: |
          git add super-${{ env.tag }} super
          git commit -m "Deploy super-${{ env.tag }} to GitHub Pages"
          git push origin gh-pages
