name: Main

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Triggers both builds and tag deployments

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Generates
        run: |
          make generate

      - name: Build Binary
        run: |
          make build

      # TODO: Fix tests and enable this
      #- name: Test Binary
      #  run: |
      #    make test

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: super
          path: bin/super

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout gh-pages branch
        run: |
          git fetch --no-tags --filter=blob:none origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Download Tagged Binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v4
        with:
          name: super
          path: /tmp/artifacts

      - name: Download Nightly Binary
        uses: actions/download-artifact@v4
        with:
          name: super-nightly
          path: /tmp/artifacts

      - name: Deploy Tagged Binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_VERSION="${GITHUB_REF##*/}"
          cp /tmp/artifacts/super super-${TAG_VERSION}
          cp /tmp/artifacts/super super

      - name: Deploy Nightly Binary
        run: |
          cp /tmp/artifacts/super super-nightly

      - name: Commit and Push Changes
        run: |
          git add super super-* super-nightly || true
          git commit -m "Deploy latest binaries to GitHub Pages"
          git push origin gh-pages || echo "No changes to push"